/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Armored Core: Project Phantasma)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80011E94u
#define func_80011E94 BootEntry  /* alias */
